package org.leonardi.bugreport.GUI;

import org.leonardi.bugreport.Database;

import javax.swing.*;
import java.io.*;


public class OpenBug extends javax.swing.JFrame {
    private javax.swing.JTextArea bugArea;
    private javax.swing.JLabel bugLabel;

    private javax.swing.JButton cancelButton;
    private javax.swing.JButton openButton;
    private javax.swing.JScrollPane jScrollPane1;

    /**
     * Creates new form NewJFrame
     */
    public OpenBug() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        bugLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bugArea = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();

        bugLabel.setText("Bug ");

        bugArea.setColumns(20);
        bugArea.setRows(5);
        jScrollPane1.setViewportView(bugArea);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    openButtonActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(270, 270, 270)
                                                                .addComponent(openButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cancelButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(bugLabel)))
                                                .addGap(0, 7, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bugLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(openButton)
                                        .addComponent(cancelButton))
                                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);

    }

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
//        bugArea.append(String.valueOf(database.bugs));
//        OpenExistingBugsList load = new OpenExistingBugsList();
//        setVisible(true);
//        load.setSize(200, 200);
//        new OpenExistingBugsList().setVisible(true);


//        for (int i = 0; i < Database.bugs.size(); i++) {
////            bugArea.setText(String.valueOf(Database.bugs.get(i).getId()));
//            bugArea.setText(String.valueOf(i));
//        }




        JFileChooser open = new JFileChooser();
        int status = open.showOpenDialog(null);
        if (status == JFileChooser.APPROVE_OPTION){
            File file = open.getSelectedFile();
            try{
                BufferedReader input = new BufferedReader(new InputStreamReader(new FileInputStream(file)));
                bugArea.read(input, "Reading File");
                JOptionPane.showMessageDialog(null, "File Read");
            } catch (Exception e){
                e.printStackTrace();
            }
        }
        else {
            System.out.println("Operation Cancelled");
        }
    }

    public void setBugArea(JTextArea bugArea) {
        this.bugArea = bugArea;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetCodeBug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetCodeBug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetCodeBug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetCodeBug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenBug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify

    // End of variables declaration
}
